# Generated by Django 5.0 on 2024-04-03 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='category',
            field=models.CharField(choices=[('toys', 'Toys'), ('food', 'Food'), ('cosmetics', 'Cosmetics'), ('clothes', 'Clothes')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('toys', 'Toys'), ('food', 'Food'), ('cosmetics', 'Cosmetics'), ('clothes', 'Clothes')], max_length=100),
        ),
    ]
