# Generated by Django 5.0 on 2024-02-24 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_appuser_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='is_verified',
            new_name='email_verified',
        ),
    ]
