export const SERVICE_PRICES = {
  Grooming: 800,
  Vaccination: 500,
  NailTrimming: 300,
};

export const BREEDS = {
  dog: [
    "German Shepherd",
    "Labrador Retriever",
    "Golden Retriever",
    "Bulldog",
    "Beagle",
    "Poodle",
    "Rottweiler",
    "Yorkshire Terrier",
    "Dachshund",
    "Boxer",
    "Siberian Husky",
    "Doberman Pinscher",
    "Great Dane",
    "Shih Tzu",
    "Pug",
    "Chihuahua",
    "Maltese",
    "Border Collie",
    "Australian Shepherd",
    "Cocker Spaniel",
  ],

  cat: [
    "Abyssinian",
    "American Shorthair",
    "Bengal",
    "Birman",
    "Bombay",
    "British Shorthair",
    "Burmese",
    "Chartreux",
    "Cornish Rex",
    "Devon Rex",
    "Egyptian Mau",
    "Exotic Shorthair",
    "Maine Coon",
    "Manx",
    "Norwegian Forest Cat",
    "Oriental",
    "Persian",
    "Ragdoll",
    "Russian Blue",
    "Siamese",
    "Sphynx",
  ],
};

export const BREED_SERVICE_CHARGE = {
  dog: {
    "German Shepherd": 1200,
    "Labrador Retriever": 1300,
    "Golden Retriever": 1400,
    Bulldog: 1100,
    Beagle: 1100,
    Poodle: 1200,
    Rottweiler: 1200,
    "Yorkshire Terrier": 1100,
    Dachshund: 1100,
    Boxer: 1200,
    "Siberian Husky": 1400,
    "Doberman Pinscher": 1200,
    "Great Dane": 1200,
    "Shih Tzu": 1150,
    Pug: 1150,
    Chihuahua: 1100,
    Maltese: 1150,
    "Border Collie": 1200,
    "Australian Shepherd": 1200,
    "Cocker Spaniel": 1150,
  },
  cat: {
    Abyssinian: 1000,
    "American Shorthair": 900,
    Bengal: 1100,
    Birman: 1050,
    Bombay: 950,
    "British Shorthair": 1100,
    Burmese: 1000,
    Chartreux: 1050,
    "Cornish Rex": 950,
    "Devon Rex": 950,
    "Egyptian Mau": 1100,
    "Exotic Shorthair": 1050,
    "Maine Coon": 1500,
    Manx: 950,
    "Norwegian Forest Cat": 1150,
    Oriental: 1050,
    Persian: 1100,
    Ragdoll: 1100,
    "Russian Blue": 1100,
    Siamese: 1100,
    Sphynx: 1500,
  },
};

export const AGRRESIVE_CHARGE = {
  Violent: 1500,
  "Semi-violent": 1250,
  "Not-violent": 1000,
  Unknown: 750,
};
