# Generated by Django 5.0 on 2024-04-11 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_is_aggressive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='is_aggressive',
            field=models.CharField(default='Unknown'),
        ),
    ]
