# Generated by Django 5.0 on 2024-04-15 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_remove_booking_service_booking_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='service',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
