# Generated by Django 5.0 on 2024-04-16 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_remove_booking_service_delete_service_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='is_aggressive',
            new_name='aggressive',
        ),
    ]
