# Generated by Django 5.0 on 2024-04-16 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_rename_is_aggressive_booking_aggressive'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='estimated_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
