# Generated by Django 5.0 on 2024-04-16 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adoptedpet',
            old_name='agreement',
            new_name='aggreement',
        ),
    ]
