# Generated by Django 5.0 on 2024-04-05 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adopt',
            name='is_adopted',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AdoptedPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adopted_date', models.DateTimeField(auto_now_add=True)),
                ('adopt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adoption.adopt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
