# Generated by Django 5.0 on 2024-04-11 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adoptedpet',
            old_name='adopt',
            new_name='adopt_id',
        ),
        migrations.RenameField(
            model_name='adoptedpet',
            old_name='user',
            new_name='user_id',
        ),
    ]
