# Generated by Django 5.0 on 2024-04-11 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0002_rename_adopt_adoptedpet_adopt_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adoptedpet',
            old_name='adopt_id',
            new_name='adopt',
        ),
        migrations.RenameField(
            model_name='adoptedpet',
            old_name='user_id',
            new_name='user',
        ),
    ]
