# Generated by Django 5.0 on 2024-04-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0003_adoptedpet_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptedpet',
            name='status',
            field=models.CharField(default='pending'),
        ),
    ]
